### PR TITLE
assignment-two

### PR DESCRIPTION
**Pull request by mandana-g**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
adding two ERDs, a response to promp3 in assignment2.md and responses to questions in assignment2.sql.
## What did you learn from the changes you have made?
practicing learning materials in different areas such as cross join, working with strings, window functions and so on.
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Some questions request was not clear to me at first. For example, I was first thinking is the Coalesce question is asking for first and second Null in rows and not the columns.
## How were these changes tested?
I cross-checked with the data in tables
## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by efantinatti — APPROVED** [review]
Dear Mandana Goudarzian

Session 1:
1 - OK.

Session 2:
2 - OK.
-- String manipulations - Q2: Just a heads up. You don't need to filter by string.

Session 3:
3 - Partial.
-- Cross Join - Q1: Query multiplies a count which leads to erroneous result.
-- DELETE - Q1: Delete won't work for the older record based on time. In this case will delete all them.
-- UPDATE - Q1: Result: no such column: product_unit.product_id

Final:
4 - Check the aforementioned points prior to merging your feature branch 'assignment-two' to 'main'.

Mark: 64 points.

**Comment by mandana-g** [comment]
Thanks for your comments @efantinatti. Following I have a few questions that I would appreciate if you clarify. Thank you.
**- Session 2:**
 Regarding the following part in string manipulation:
 "/* 2. Filter the query to show any product_size value that contain a number with REGEXP. */" 
  I added the filter part. Am I doing anything wrong here?
**- Session 3:**
-- Cross Join: thanks for the point, I will modify that.
-- DELETE: I didn't get what is exactly the issue in this part? Or even maybe not sure about the question itself. 
-- UPDATE: There was a typo in "unit"/"units" that I will fix.

**Comment by efantinatti** [comment]
Hi @mandana-g thanks for your questions and see my observations below.

- Session 2:
Regarding the following part in string manipulation:
"/* 2. Filter the query to show any product_size value that contain a number with REGEXP. */"
[Ernani Fantinatti] Here you just need to filter by regex, where is not need to perform othee filtering.

I added the filter part. Am I doing anything wrong here?
- Session 3:
-- DELETE: I didn't get what is exactly the issue in this part? Or even maybe not sure about the question itself.
[Ernani Fantinatti] Here the question asks for the older record based on time it was entered. In your case you are deleting the same product based on the index number and not based in the time of registration / entry.

**Comment by mandana-g** [comment]
Thanks for the explanations @efantinatti. Issues are fixed and the PR is updated, please let me know if they are as expected. Thank you.

**Comment by efantinatti** [comment]
> Thanks for the explanations @efantinatti. Issues are fixed and the PR is updated, please let me know if they are as expected. Thank you.

Looks good @mandana-g. Great job!

**Pull request merged**
